
CPU       = max32660
CPU_MODEL = MAX32660H5QR

# defined MCU peripherals (in alphabetical order)
FEATURES_PROVIDED += periph_gpio
#FEATURES_PROVIDED += periph_uart   must build with  CONTINUE_ON_EXPECTED_ERRORS=1

