
# define stellaris specific flags and includes
export STELLARISWARE = $(RIOTCPU)/max32_common/include/vendor

# define build specific options
CFLAGS += -I$(STELLARISWARE) -DPART_$(CPU_MODEL) -c -DTARGET_IS_BLIZZARD_RA1

