
ROM_START_ADDR = 0
RAM_START_ADDR = 0x20000000

ROM_LEN = 0x40000   # 256K
RAM_LEN = 0x18000   #  96K

LINKER_SCRIPT ?= cortexm.ld

include $(RIOTMAKE)/arch/cortexm.inc.mk

#include $(RIOTCPU)/stellaris_common/Makefile.include
include $(RIOTCPU)/max32_common/Makefile.include

